#!/usr/bin/env python3
"""Generate Awareen's scenery and logo drawables from one set of layer definitions.

Writes, under app/src/main/res/drawable/:
  scene_header.xml            night sky over the mountains (home header, Settings preview)
  awareen_logo.xml            the mountain mark, clipped to a circle (About screen)
  ic_launcher_background.xml  adaptive-icon sky
  ic_launcher_foreground.xml  adaptive-icon scene
  ic_launcher_monochrome.xml  themed-icon silhouette (Android 13+)

Usage:
  scripts/generate_scenery.py                 # regenerate the drawables
  scripts/generate_scenery.py --preview DIR   # also write SVG previews to DIR
  scripts/generate_scenery.py --png           # also export docs/awareen.png and the
                                              # Play Store icon (needs rsvg-convert)

Only the standard library is needed. Edit the layer definitions below and rerun;
never hand-edit the generated XML, the next run overwrites it.
"""
import argparse
import os
import random
import re
import subprocess

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(REPO, "app", "src", "main", "res")

# Must match res/values/colors.xml. Flat fills reference these by @color name;
# gradients and SVG previews need the literal values.
PAL = {
    "app_background": "#0F1613",
    "scene_sky_glow": "#1D2D28",
    "scene_ridge_far": "#2C433B",
    "scene_ridge_mid": "#203229",
    "scene_snow": "#ECE8DC",
    "scene_meadow": "#9DBF86",
}

# A layer is {"d": path, "fill": colour name | gradient, "alpha": 0..1}.
# A gradient is ("linear", x1, y1, x2, y2, [(offset, colour name, alpha), ...]).


def hexa(name, a=1.0):
    return "#%02X%s" % (round(a * 255), PAL[name].lstrip("#"))


def svg(w, h, layers, clip=None, transform=None):
    defs, body = [], []
    for i, L in enumerate(layers):
        f = L["fill"]
        if isinstance(f, tuple):
            stops = "".join('<stop offset="%s" stop-color="%s" stop-opacity="%s"/>' % (o, PAL[n], a) for o, n, a in f[5])
            defs.append('<linearGradient id="g%d" gradientUnits="userSpaceOnUse" x1="%s" y1="%s" x2="%s" y2="%s">%s</linearGradient>'
                        % ((i,) + f[1:5] + (stops,)))
            fill = "url(#g%d)" % i
        else:
            fill = PAL[f]
        body.append('<path d="%s" fill="%s" fill-opacity="%s"/>' % (L["d"], fill, L.get("alpha", 1)))
    g = "".join(body)
    if transform:
        g = '<g transform="%s">%s</g>' % (transform, g)
    if clip:
        defs.append('<clipPath id="c"><path d="%s"/></clipPath>' % clip)
        g = '<g clip-path="url(#c)">%s</g>' % g
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %s %s" width="%s" height="%s"><defs>%s</defs>%s</svg>'
            % (w, h, w, h, "".join(defs), g))


def vector(w, h, layers, clip=None, group=None, comment=""):
    out = ['<?xml version="1.0" encoding="utf-8"?>']
    if comment:
        out.append("<!--\n%s\n    Generated by scripts/generate_scenery.py; do not edit by hand.\n-->" % comment)
    out.append('<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
               '    xmlns:aapt="http://schemas.android.com/aapt"\n'
               '    android:width="%sdp"\n    android:height="%sdp"\n'
               '    android:viewportWidth="%s"\n    android:viewportHeight="%s">' % (w, h, w, h))
    ind = "    "
    if clip or group:
        attrs = "".join(' android:%s="%s"' % kv for kv in (group or {}).items())
        out.append(ind + "<group%s>" % attrs)
        ind += "    "
        if clip:
            out.append(ind + '<clip-path android:pathData="%s" />' % clip)
    for L in layers:
        f = L["fill"]
        alpha = L.get("alpha", 1)
        a = ' android:fillAlpha="%s"' % alpha if alpha != 1 else ""
        if isinstance(f, tuple):
            out.append(ind + '<path android:pathData="%s"%s>' % (L["d"], a))
            out.append(ind + '    <aapt:attr name="android:fillColor">')
            out.append(ind + '        <gradient android:type="linear" android:startX="%s" android:startY="%s" android:endX="%s" android:endY="%s">' % f[1:5])
            for o, n, ga in f[5]:
                out.append(ind + '            <item android:offset="%s" android:color="%s" />' % (o, hexa(n, ga)))
            out.append(ind + "        </gradient>")
            out.append(ind + "    </aapt:attr>")
            out.append(ind + "</path>")
        else:
            out.append(ind + '<path android:fillColor="@color/%s" android:pathData="%s"%s />' % (f, L["d"], a))
    if clip or group:
        out.append("    </group>")
    out.append("</vector>\n")
    return "\n".join(out)


def circ(cx, cy, r):
    return "M%s,%s m-%s,0 a%s,%s 0 1,0 %s,0 a%s,%s 0 1,0 -%s,0 Z" % (cx, cy, r, r, r, 2 * r, r, r, 2 * r)


def map_y(d, fy):
    """Map every y coordinate of an absolute M/L/Q/C/S/V path through fy."""
    out, cmd, idx = [], None, 0
    for tok in re.findall(r"[A-Za-z]|-?[0-9.]+", d):
        if tok.isalpha():
            cmd, idx = tok, 0
            out.append(tok)
            continue
        v = float(tok)
        if cmd == "V" or (cmd in "MLQCS" and idx % 2 == 1):
            v = fy(v)
        idx += 1
        out.append("%g" % v)
    return re.sub(r" (?=[A-Za-z])|(?<=[A-Za-z]) ", "", " ".join(out)).replace(" ", ",")


# ---------------------------------------------------------------- header scene
# 400 x 360 dp, shown at scale ~1 on phones (centerCrop). The home card
# overlaps the bottom 28dp, so its top edge falls at y=332.
W, H = 400, 360

# The ranges are drawn on a reference canvas (hero apex at y=146) and then
# placed low, below the wordmark: the apex lands at APEX_Y and heights are
# scaled by SQUASH so every layer still shows above the card.
APEX_Y, SQUASH = 268, 0.6


def place(y):
    return round(APEX_Y + (y - 146) * SQUASH, 2)


header = [{"d": "M0,0 H%s V%s H0 Z" % (W, H), "fill": ("linear", 0, 0, 0, 300, [(0, "app_background", 1), (1, "scene_sky_glow", 1)])}]

rnd = random.Random(7)  # fixed seed: the same stars on every run
for _ in range(22):
    x, y = rnd.uniform(8, 392), rnd.uniform(10, 150)
    r, a = rnd.choice([0.7, 0.9, 1.1]), rnd.choice([0.18, 0.28, 0.4])
    header.append({"d": circ(round(x, 1), round(y, 1), r), "fill": "scene_snow", "alpha": a})

ranges = [
    # far range with the hero peak (the logo's peak) and a smaller snowcap
    {"d": "M0,214 L38,199 L70,206 L112,183 L150,198 L192,170 L222,182 L250,146 L282,178 L314,166 L352,186 L400,174 V300 H0 Z", "fill": "scene_ridge_far"},
    {"d": "M250,146 L265.5,163 L258.5,160 L252.5,167 L246,160.5 L237.5,162 Z", "fill": "scene_snow", "alpha": 0.95},
    {"d": "M192,170 L200.5,178 L195,176.5 L190,180 L186,176 Z", "fill": "scene_snow", "alpha": 0.55},
    # mist lying in the valley
    {"d": "M0,196 H%s V236 H0 Z" % W, "fill": ("linear", 0, 196, 0, 236, [(0, "scene_snow", 0), (0.6, "scene_snow", 0.05), (1, "scene_snow", 0)])},
    {"d": "M0,232 L40,219 L80,227 L124,208 L166,225 L206,213 L248,229 L292,204 L338,221 L372,212 L400,218 V300 H0 Z", "fill": "scene_ridge_mid"},
]
for L in ranges:
    L["d"] = map_y(L["d"], place)
    f = L["fill"]
    if isinstance(f, tuple):
        L["fill"] = ("linear", f[1], place(f[2]), f[3], place(f[4]), f[5])
header += ranges

# The ranges rest on a soft rolling foreground hill in exactly the page colour:
# a clean base that merges into the page with no visible edge.
header.append({"d": "M0,318 C60,309 112,323 172,314 S282,305 332,316 S388,322 400,317 V%s H0 Z" % H, "fill": "app_background"})

# ---------------------------------------------------------------- logo
# Designed on the 108 adaptive-icon canvas: moon, far ridge with the hero
# peak and snowcap, mid ridge, meadow.
SKY = ("linear", 0, 0, 0, 108, [(0, "scene_sky_glow", 1), (1, "app_background", 1)])
logo_scene = [
    {"d": circ(76, 32, 4.5), "fill": "scene_snow"},
    {"d": "M-40,64 L16,54 L28,60 L54,30 L80,60 L92,52 L148,62 V160 H-40 Z", "fill": "scene_ridge_far"},
    {"d": "M54,30 L65.5,43.2 L59.5,41.6 L54,47.4 L48.5,41.6 L42.5,43.2 Z", "fill": "scene_snow"},
    {"d": "M-40,76 L0,74 L22,64 L40,70 L56,62 L74,70 L92,64 L148,72 V160 H-40 Z", "fill": "scene_ridge_mid"},
    {"d": "M-40,90 Q0,78 30,76 Q46,75 58,80 Q86,86 108,76 Q130,68 148,76 V160 H-40 Z", "fill": "scene_meadow"},
]
# Themed (monochrome) icon: the system tints it, so only shape and alpha matter.
logo_mono = [
    {"d": circ(76, 32, 4.5), "fill": "scene_snow"},
    {"d": "M-40,64 L16,54 L28,60 L54,30 L80,60 L92,52 L148,62 L148,72 L92,64 L74,70 L56,62 L40,70 L22,64 L0,74 L-40,76 Z", "fill": "scene_snow", "alpha": 0.55},
    {"d": "M-40,90 Q0,78 30,76 Q46,75 58,80 Q86,86 108,76 Q130,68 148,76 V160 H-40 Z", "fill": "scene_snow"},
    {"d": "M54,30 L65.5,43.2 L59.5,41.6 L54,47.4 L48.5,41.6 L42.5,43.2 Z", "fill": "scene_snow"},
]
FULL = "M0,0 H108 V108 H0 Z"
CIRCLE = circ(54, 54, 54)
logo_full = [{"d": FULL, "fill": SKY}] + logo_scene
# Adaptive-icon foreground: scaled into the visible 72dp centre, ridges and
# meadow bleeding past the edges so the mask never shows a gap.
ICON_GROUP = {"scaleX": "0.82", "scaleY": "0.82", "translateX": "9.72", "translateY": "11.5"}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--preview", metavar="DIR", help="also write SVG previews to DIR")
    ap.add_argument("--png", action="store_true", help="also export docs/awareen.png and the Play Store icon")
    args = ap.parse_args()

    def drawable(name, text):
        with open(os.path.join(RES, "drawable", name), "w") as fh:
            fh.write(text)

    drawable("scene_header.xml", vector(W, H, header, comment=
        "    Night sky over the mountains: the backdrop at the top of the home\n"
        "    screen and behind the timer preview in Settings. Distant ridges are\n"
        "    lighter, like atmospheric haze, and the range rests on a hill in the\n"
        "    page colour so the scene melts into the page."))
    drawable("awareen_logo.xml", vector(108, 108, logo_full, clip=CIRCLE, comment=
        "    The Awareen mark: a snow-capped peak under a quiet moon, with a meadow\n"
        "    in front. Same artwork as the launcher icon, clipped to a circle."))
    drawable("ic_launcher_background.xml", vector(108, 108, [{"d": FULL, "fill": SKY}]))
    drawable("ic_launcher_foreground.xml", vector(108, 108, logo_scene, group=ICON_GROUP))
    drawable("ic_launcher_monochrome.xml", vector(108, 108, logo_mono, group=ICON_GROUP))

    square = svg(108, 108, logo_full)  # full bleed: stores and sites apply their own masks
    if args.preview:
        os.makedirs(args.preview, exist_ok=True)
        for name, text in [("header.svg", svg(W, H, header)),
                           ("logo.svg", svg(108, 108, logo_full, clip=CIRCLE)),
                           ("logo_square.svg", square)]:
            with open(os.path.join(args.preview, name), "w") as fh:
                fh.write(text)
    if args.png:
        for size, dest in [(1024, os.path.join(REPO, "docs", "awareen.png")),
                           (512, os.path.join(REPO, "app", "src", "main", "ic_launcher-playstore.png"))]:
            subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", dest],
                           input=square.encode(), check=True)
    print("scenery written to", os.path.relpath(os.path.join(RES, "drawable"), REPO))


if __name__ == "__main__":
    main()
